### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by reintroducing** [paulwib/dss-parser-variable#1]
Hello,
I'd like to use this in a project and I tried to implement it today but it doesn't seem to work.  I get the Colors section output but the variables themselves do not get output.  Do you by any chance have a repo where this is working?

**Comment by paulwib** [comment]
Hi @reintroducing - do you have an example of the DSS block it is failing to parse?

**Comment by reintroducing** [comment]
Hi @paulwib I've uploaded an example here: http://dev.reintroducing.com/2015/dss-parser-variable.zip

You will need a few things: 
1) The node modules to install are dss, dss-parser-variable, glob, read-multiple-files.  I didn't include a package.json because I was just testing all this out so I have not truly set it up properly inside of my larger project, this is just an example I was using to test that everything works.

2) You will note that I changed the comment to accept ~ as the separator rather than - because my variables have dashes in them (so yes, temporarily I had edited the source of this plugin just to test if that was the problem).  If you use it as is however, you can just remove the dashes from the @variable portion that are names and replace the ~ with the original - and see that it still doesn't work.

3) Even when I had the simple example that you show on the front page it didn't work for me.  Note that I'm using Sass not CSS as obviously I should be doing since these are variables that don't exist in CSS.  You should update your readme to reflect this as well.

Just run `node index.js` in terminal and you will see an output dss.json file.  In there you will see the Colors block but no colors present.

Let me know if you have any questions.

**Comment by paulwib** [comment]
Could you just show me the DSS block that's causing problems? Then I can run that through the unit tests.

**Comment by reintroducing** [comment]
Here you go:

```
/**
  * @name Colors
  * @variable off-white ~ Off White
  * @variable faint-gray ~ Faint Gray
  */
```

In your case you can turn it into this since you don't have my edited version:

```
/**
  * @name Colors
  * @variable offwhite - Off White
  * @variable faintgray - Faint Gray
  */
```

**Comment by paulwib** [comment]
Hm..that should work. Are the variables actually defined in the file? The DSS blocks will be ignored if ti cannot find the variables in the file. 

BTW I released a new version to support hyphens in variable names - that should work as expected now. 

I also updated the README example and added a test that it works.

**Comment by reintroducing** [comment]
Works perfectly now, thank you very much!  Appreciate the help, great little parser.
